### ISSUE TITLE
Make exception verbosity configurable?

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/GPUCompiler.jl#142]
Currently exception reporting is done based on Julia's debug level, however on the host, stackframes are shown regardless of the debug level (it would be silly to not get stacktraces just because you aren't using `julia-debug`). Could we make verbose exceptions (with stacktraces) configurable based on some job parameter?

**Comment by jpsamaroo** [comment]
Nevermind, I just realized that `julia -g2` is a thing, which is more than sufficient!

**Comment by maleadt** [comment]
I was afraid the constants and lots of print calls would bloat the code and module size, so left it out by default. Maybe we can come up with something better once we have a `hostcall` mechanism across all stacks, but that's probably not for soon.
