### ISSUE TITLE
World age behavior different from Base

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/GPUCompiler.jl#146]
## Wanted behavior

Given the following function, which defines a module and function at run time, and tries to call them:

```julia
function main()
    arr = zeros(Int)

    @gensym mod_name
    mod = @eval(Main, module $mod_name end)
    @eval mod begin
        function kernel(ptr)
            ptr[] = 1
            return
        end
    end

    mod.kernel(arr)
    @assert Array(arr)[] == 1
end
```

This results in a MethodError due to world age issues:

```
ERROR: MethodError: no method matching kernel(::Array{Int64, 0})
The applicable method may be too new: running in world age 29740, while current world is 29744.
Closest candidates are:
  kernel(::Any) at /home/tim/Julia/pkg/CUDA/wip.jl:9 (method too new to be called from this world context.)
```

To call this function, we need `invokelatest`.

---

## Inconsistency 1

If we replace this by the CUDA equivalent, we can call this function perfectly fine:

```julia
function main()
    arr = CuArray(zeros(Int))

    @gensym mod_name
    mod = @eval(Main, module $mod_name end)
    @eval mod begin
        function kernel(ptr)
            ptr[] = 1
            return
        end
    end

    @cuda mod.kernel(arr)
    @assert Array(arr)[] == 1
end
```

This shouldn't be possible, and we should throw a MethodError instead.

## Inconsistency 2

If we *redefine* the method in that module, our method invalidation breaks:

```julia
function main()
    # same as before

    arr = CuArray(zeros(Int))

    @gensym mod_name
    mod = @eval(Main, module $mod_name end)
    @eval mod begin
        function kernel(ptr)
            ptr[] = 1
            return
        end
    end

    @cuda mod.kernel(arr)
    @assert Array(arr)[] == 1


    # redefine

    @eval mod begin
        function kernel(ptr)
            ptr[] = 2
            return
        end
    end

    @cuda mod.kernel(arr)
    @assert Array(arr)[] == 2
end
```

```
ERROR: AssertionError: (Array(arr))[] == 2
```

---

To fix the first inconsistency, I think we need to use a proper world age in the generated function that looks up the MethodInstance to compile, i.e., get rid of the `typemax(UInt)` here: https://github.com/JuliaGPU/GPUCompiler.jl/blob/3edaebdc7d3a26094664f3acb16ff4bcad8c4784/src/cache.jl#L70-L75

However, we can't just use `get_world_counter()` there, as this generator runs in a newer world where the kernel has been defined already. Maybe we need an intrinsic that bakes the world age at inference time into the AST, to pass to `cached_compilation` such that it can look up the method in the correct world? @vtjnash, any thoughts?

For the second inconsistency, or issue really, I'm not sure what's happening here. @vchuravy, you looked at this last time, any ideas?

**Comment by maleadt** [comment]
For the first inconsistency, we probably need:

```patch
diff --git a/src/cache.jl b/src/cache.jl
index a69a9cd..5347f86 100644
--- a/src/cache.jl
+++ b/src/cache.jl
@@ -72,7 +72,7 @@ const specialization_counter = Ref{UInt}(0)
                                        compiler::Function, linker::Function) where {f,tt}
     # get a hold of the method and code info of the kernel function
     sig = Tuple{f, tt.parameters...}
-    mthds = _methods_by_ftype(sig, -1, typemax(UInt))
+    mthds = _methods_by_ftype(sig, -1, Base.get_world_counter())
```

Still, that results in a too new world age. Say we define `foo()` in world 1 to call `@cuda kernel()`, but only define `kernel()` in world 2. If we then _call_ `foo()` after having defined `kernel()`, we should get a world age error, but since the compiler is only invoked at run time `get_world_counter()` returns 2 so we _can_ look up `kernel()`.

@vtjnash Could you chime in here? Is there a mechanism to query the world age bounds that corresponds with the world in which a function was defined (as opposed to the _current_ world counter)?

**Comment by vtjnash** [comment]
Yes, this needs to be added to the `@generated` internal API
