### ISSUE TITLE
`ErrorException("setfield!: const field .max_world of type CodeInstance cannot be changed")`

### ISSUE THREAD

**Issue by KristofferC** [JuliaGPU/GPUCompiler.jl#361]
On 1.9: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c6440b9_vs_d0156b5/Checkpointing.primary.log

**Comment by maleadt** [comment]
That code https://github.com/JuliaGPU/GPUCompiler.jl/blob/754619dc36fd3f76ceffe5db4747773534c3ef29/src/jlgen.jl#L69-L75 is basically the Julia translation of https://github.com/JuliaLang/julia/blob/master/src/gf.c#L1445-L1455

I guess this was introduced by https://github.com/JuliaLang/julia/pull/46203? cc @pchintalapudi
