### ISSUE TITLE
min_enabled_level is at risk of invalidations

### ISSUE THREAD

**Issue by vtjnash** [JuliaGPU/GPUCompiler.jl#431]
If you compare the hand-rolled version of logging to what we have defined Base, we see this code is missing invokelatest calls in critical places, to ensure inference stability. That breaks here under SnoopCompile when loading the package from:
https://github.com/JuliaGPU/GPUCompiler.jl/blame/7c4855ed71dff30e12d177b46b824d2f890c9acb/src/utils.jl#L56
```
inserting min_enabled_level(logger::LoggingExtras.LevelOverrideLogger) @ LoggingExtras ~/.julia/packages/LoggingExtras/zT9ZU/src/overridelogger.jl:23 invalidated:
   mt_backedges: 1: signature Tuple{typeof(Base.CoreLogging.min_enabled_level), Any} triggered MethodInstance for Core.Compiler.add_remark!(::GPUCompiler.GPUInterpreter, ::Core.Compiler.InferenceState, ::String) (0 children)
```

**Comment by maleadt** [comment]
Ah, good catch. I'd rather we could get rid of these macros, but they seem like the only way to safely print from within the compiler (i.e., without triggering task switches because of using Julia's buffered I/O). Unless you have other ideas?
