### ISSUE TITLE
How to set fast math for CUDA

### ISSUE THREAD

**Issue by Zentrik** [JuliaGPU/GPUCompiler.jl#491]
It seems to me that fast math is set in this line and as `--math-mode` has been disabled (https://github.com/JuliaLang/julia/pull/41638) there is no way currently to use fast math.
https://github.com/JuliaGPU/GPUCompiler.jl/blob/15f00778eb0a2daa5960c566a161adada1b29bf6/src/ptx.jl#L427

Perhaps fast math should be set by the user similarly to `max_regs`.

**Comment by vchuravy** [comment]
You can use the `@fastmath` macro locally.

**Comment by maleadt** [comment]
`@fastmath` being a syntactical transformation, https://github.com/JuliaLang/julia/issues/26828, we cannot implement this as an option to `@cuda` without reimplementing it all using overlay tables. Not saying that shouldn't happen, and I'd be in favor, it's just that this shouldn't happen in CUDA.jl.

**Comment by Zentrik** [comment]
Does `@fastmath` enable flushing denormals and the other stuff here.
https://github.com/JuliaGPU/GPUCompiler.jl/blob/15f00778eb0a2daa5960c566a161adada1b29bf6/src/ptx.jl#L427-L441
That's what I cared about, I'm already using `@fastmath` to use the faster versions of functions.

It doesn't seem to, e.g.
```jl
@fastmath function kernel!(y, x)
     i = threadIdx().x
     @inbounds y[i] = sqrt(x[i])
     
     return nothing
 end
x = CuArray(Float32[])
@device_code_ptx @cuda launch=false always_inline=true kernel!(x, x)
```
Looking at the ptx of this I see `sqrt.rn.f32     %f2, %f1;` whereas if I run a fork of GPUCompiler.jl and set `fast_math` to true, I get `sqrt.approx.ftz.f32     %f2, %f1;` and the sass code looks significantly better.

**Comment by Zentrik** [comment]
`@fastmath sqrt` and `sqrt` compile to `@llvm.sqrt.f32` in llvm as CUDA doesn't define a fastmath sqrt, so perhaps not the best example but I think my point still stands.

**Comment by maleadt** [comment]
> Does `@fastmath` enable flushing denormals and the other stuff here.

Ah yes, that kind of stuff we should be able to control.

> Doing `@fastmath 1 / x[i]` I see with `fast_math = false` `div.approx` in the ptx and with `fast_math=true` `div.approx.ftz`.

That won't be affected by the proposed `fast_math` flag though, which only affects the code from `libdevice`. IIUC Julia itself should change the emission of the `fdiv` LLVM IR instruction, adding appropriate fast-math flags (not saying that's implemented, but it's the level where this should be happening).

**Comment by Zentrik** [comment]
Thanks
