### ISSUE TITLE
pkgversion can return nothing.

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/GPUCompiler.jl#593]
Seen on CI with `⌃ [61eb1bfa] GPUCompiler v0.26.5`

```
 Julia Version 1.12.0-DEV.799
Commit 8791d54d142 (2024-06-28 11:07 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × AMD EPYC 7763 64-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```

```
ERROR: LoadError: InitError: FieldError: type Nothing has no field major
Stacktrace:
  [1] getproperty
    @ ./Base.jl:49 [inlined]
  [2] __init__()
    @ GPUCompiler ~/.julia/packages/GPUCompiler/nWT2N/src/GPUCompiler.jl:64
  [3] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1305
  [4] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1293
```

https://github.com/JuliaGPU/GPUCompiler.jl/blob/39beabbef9ef047675ac700f724b741570c324ca/src/GPUCompiler.jl#L64

https://github.com/JuliaGPU/KernelAbstractions.jl/actions/runs/9704681162/job/26812207150?pr=487#step:6:183

**Comment by maleadt** [comment]
Related: https://github.com/JuliaGPU/GPUCompiler.jl/pull/589

Is this in a plain environment (i.e., not using PackageCompiler or sysimages or anything)? 

From the `Base.pkgversion` docs:

> Return the version of the package that imported module m, or nothing if m was not imported from a package.

That covers the PackageCompiler/sysimg case.

**Comment by vchuravy** [comment]
> Is this in a plain environment

Should be this, was just normal CI

**Comment by giordano** [comment]
For the record, I also ran into this issue in Julia v1.11 with a plain environment, not PackageCompiler/sysimg.
