### ISSUE TITLE
problem in Woodpecker CI

### ISSUE THREAD

**Issue by AdamWysokinski** [JuliaGPU/GPUCompiler.jl#640]
Hi,
Woodpecker CI (used e.g. by Codeberg) exports variable CI (default value "woodpecker"). GPUCompiler expects this variable to be a Bool value and throws an error while precompiling on default. A hackish solution is to change its value to "1" prior to running Julia. This helps, but may disturb further Woodpecker workflow, if the default $CI value would be expected. Could you please take a look into this minor issue?
ATB, Adam

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/GPUCompiler.jl/commit/61249299eb52c97b232e57e8baf4a2bc0392b9a1
